[build]
working_directory = "Decola-Tech-2025/"

[phases.setup]
nixPkgs = ["gradle"]
commands = ["chmod +x ./gradlew"]

[phases.build]
commands = ["./gradlew build"]

[phases.start]
commands = ["java -jar build/libs/Decola-Tech-2025-0.0.1-SNAPSHOT.jar"]
